// <auto-generated />
using System;
using GoodHamburgerProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoodHamburgerProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoodHamburgerProject.Models.AccompanimentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Accompaniments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Active = true,
                            Name = "Batata Frita",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Active = true,
                            Name = "Refrigerante",
                            Price = 2.50m
                        });
                });

            modelBuilder.Entity("GoodHamburgerProject.Models.BurgerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Burgers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Active = true,
                            Name = "X Burger",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Active = true,
                            Name = "X Egg",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Active = true,
                            Name = "X Bacon",
                            Price = 7.00m
                        });
                });

            modelBuilder.Entity("GoodHamburgerProject.Models.DiscountItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DiscountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId", "ProductId")
                        .IsUnique();

                    b.ToTable("DiscountItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1d1d1d1-d1d1-d1d1-d1d1-d1d1d1d1d1d1"),
                            DiscountId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ProductType = 1
                        },
                        new
                        {
                            Id = new Guid("d2d2d2d2-d2d2-d2d2-d2d2-d2d2d2d2d2d2"),
                            DiscountId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ProductId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ProductType = 2
                        },
                        new
                        {
                            Id = new Guid("d3d3d3d3-d3d3-d3d3-d3d3-d3d3d3d3d3d3"),
                            DiscountId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ProductId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ProductType = 2
                        },
                        new
                        {
                            Id = new Guid("e1e1e1e1-e1e1-e1e1-e1e1-e1e1e1e1e1e1"),
                            DiscountId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ProductType = 1
                        },
                        new
                        {
                            Id = new Guid("e2e2e2e2-e2e2-e2e2-e2e2-e2e2e2e2e2e2"),
                            DiscountId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            ProductId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ProductType = 2
                        },
                        new
                        {
                            Id = new Guid("f1f1f1f1-f1f1-f1f1-f1f1-f1f1f1f1f1f1"),
                            DiscountId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ProductType = 1
                        },
                        new
                        {
                            Id = new Guid("f2f2f2f2-f2f2-f2f2-f2f2-f2f2f2f2f2f2"),
                            DiscountId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            ProductId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ProductType = 2
                        },
                        new
                        {
                            Id = new Guid("e1111111-1111-1111-1111-111111111111"),
                            DiscountId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProductType = 1
                        },
                        new
                        {
                            Id = new Guid("e1111111-2222-1111-1111-111111111111"),
                            DiscountId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            ProductId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ProductType = 2
                        },
                        new
                        {
                            Id = new Guid("e1111111-3333-1111-1111-111111111111"),
                            DiscountId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            ProductId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ProductType = 2
                        },
                        new
                        {
                            Id = new Guid("e2222222-1111-2222-2222-222222222222"),
                            DiscountId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProductType = 1
                        },
                        new
                        {
                            Id = new Guid("e2222222-2222-2222-2222-222222222222"),
                            DiscountId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            ProductId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ProductType = 2
                        },
                        new
                        {
                            Id = new Guid("e3333333-1111-3333-3333-333333333333"),
                            DiscountId = new Guid("d3333333-3333-3333-3333-333333333333"),
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProductType = 1
                        },
                        new
                        {
                            Id = new Guid("e3333333-2222-3333-3333-333333333333"),
                            DiscountId = new Guid("d3333333-3333-3333-3333-333333333333"),
                            ProductId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ProductType = 2
                        },
                        new
                        {
                            Id = new Guid("f1111111-1111-1111-1111-111111111111"),
                            DiscountId = new Guid("d4444444-4444-4444-4444-444444444444"),
                            ProductId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProductType = 1
                        },
                        new
                        {
                            Id = new Guid("f1111111-2222-1111-1111-111111111111"),
                            DiscountId = new Guid("d4444444-4444-4444-4444-444444444444"),
                            ProductId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ProductType = 2
                        },
                        new
                        {
                            Id = new Guid("f1111111-3333-1111-1111-111111111111"),
                            DiscountId = new Guid("d4444444-4444-4444-4444-444444444444"),
                            ProductId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ProductType = 2
                        },
                        new
                        {
                            Id = new Guid("f2222222-1111-2222-2222-222222222222"),
                            DiscountId = new Guid("d5555555-5555-5555-5555-555555555555"),
                            ProductId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProductType = 1
                        },
                        new
                        {
                            Id = new Guid("f2222222-2222-2222-2222-222222222222"),
                            DiscountId = new Guid("d5555555-5555-5555-5555-555555555555"),
                            ProductId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ProductType = 2
                        },
                        new
                        {
                            Id = new Guid("f3333333-1111-3333-3333-333333333333"),
                            DiscountId = new Guid("d6666666-6666-6666-6666-666666666666"),
                            ProductId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProductType = 1
                        },
                        new
                        {
                            Id = new Guid("f3333333-2222-3333-3333-333333333333"),
                            DiscountId = new Guid("d6666666-6666-6666-6666-666666666666"),
                            ProductId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ProductType = 2
                        });
                });

            modelBuilder.Entity("GoodHamburgerProject.Models.DiscountModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.ToTable("Discounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Active = true,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Combo Completo",
                            Percentage = 0.20m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Active = true,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Combo Burger + Refri",
                            Percentage = 0.15m
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Active = true,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Combo Burger + Batata",
                            Percentage = 0.10m
                        },
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            Active = true,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Combo X Egg Completo",
                            Percentage = 0.20m
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222222"),
                            Active = true,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Combo X Egg + Refri",
                            Percentage = 0.15m
                        },
                        new
                        {
                            Id = new Guid("d3333333-3333-3333-3333-333333333333"),
                            Active = true,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Combo X Egg + Batata",
                            Percentage = 0.10m
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-4444-444444444444"),
                            Active = true,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Combo X Bacon Completo",
                            Percentage = 0.20m
                        },
                        new
                        {
                            Id = new Guid("d5555555-5555-5555-5555-555555555555"),
                            Active = true,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Combo X Bacon + Refri",
                            Percentage = 0.15m
                        },
                        new
                        {
                            Id = new Guid("d6666666-6666-6666-6666-666666666666"),
                            Active = true,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Combo X Bacon + Batata",
                            Percentage = 0.10m
                        });
                });

            modelBuilder.Entity("GoodHamburgerProject.Models.OrderItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "ProductId")
                        .IsUnique();

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("GoodHamburgerProject.Models.OrderModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Discount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("GoodHamburgerProject.Models.DiscountItemModel", b =>
                {
                    b.HasOne("GoodHamburgerProject.Models.DiscountModel", "Discount")
                        .WithMany("Items")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");
                });

            modelBuilder.Entity("GoodHamburgerProject.Models.OrderItemModel", b =>
                {
                    b.HasOne("GoodHamburgerProject.Models.OrderModel", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GoodHamburgerProject.Models.DiscountModel", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GoodHamburgerProject.Models.OrderModel", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
